source 'https://rubygems.org'
ruby '2.1.3'

gem 'sinatra', '~> 1.4.5'
gem 'haml', '~> 4.0.5'
gem 'rest-client', '~> 1.7.2'
gem 'coffee-script', '~> 2.3.0'
gem 'libv8', '~> 3.16'
gem 'therubyracer', '~> 0.12', require: 'v8'
